# Dockerfile.api
# Use an official lightweight Python image
FROM python:3.10-slim

# Prevent Python from buffering stdout/stderr
ENV PYTHONUNBUFFERED=1

# Set working directory inside container
WORKDIR /app

# Copy project files into the container
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# The CMD line is set for Flask, binding to the port Render provides
CMD ["gunicorn", "--bind", "0.0.0.0:$PORT", "app:app"]